config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do #routing errorが出たのでscope moduleを付けておきました。
    root to: 'homes#top'
    get "about"=>"homes#about"

    get 'customers/mypage'=>"customers#show"
    get "customers/mypage/edit"=>"customers#edit"
    patch "customers/mypage"=>"customers#update"
    get 'customers/mypage/confirm'=>"customers#confirm"
    patch 'customers/mypage/withdraw'=>"customers#withdraw"

    post 'orders/confirm'=>'orders#confirm'
    get "orders/complete"=>"orders#complete"
    resources :orders, only: [:new, :create, :index, :show]


    delete "cart_items/destroy_all"=>"cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
  end

  namespace :admin do
    get  "/"=>"homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :shipping_post_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

  def address_display
  '〒' + shipping_post_code + ' ' + shipping_address + ' ' + shipping_name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.item_total_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

#以下バリデーション　数字のみ漢字のみカナのみなど
  validates :telephone_number, numericality: {only_integer: true}, length: { in: 10..11}
  validates :post_cord, numericality: {only_integer: true}, length: { is: 7}
  validates :last_name, format:{with: /\p{Han}/}
  validates :first_name, format:{with: /\p{Han}/}
  validates :last_name_kana, format:{with: /\A[ァ-ヶー]+\z/}
  validates :first_name_kana, format:{with: /\A[ァ-ヶー]+\z/}

  def address_display
  '〒' + post_cord + ' ' + address + ' '
  end
  
  def fullname
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items
  has_many :order_details
  has_many :orders, through: :order_details #n:mの関係を表現するアソシエーション。
  belongs_to :genre

  #バリデーション
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price_before_tax, presence: true
  
  #税込表示価格
  def item_total_price
    (price_before_tax*1.1).floor
  end

  #カート内で商品の画像を表示させる
  def display_image
    if image.attached?
      image.variant(resize_to_limit: [100, 100]).processed
    else
      file_path = Rails.root.join('app/assets/images/no_image.png')
      file_path.to_s
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, through: :order_details #n:mの関係を表現するアソシエーション。
  has_many :order_details, dependent: :destroy

  enum payment: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting_payment: 0,
    confirm_payment: 1,
    shipped: 2,
    out_of_delivery: 3,
    delivered: 4
  }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

  def total_piece
    total = 0
    order_details.each do |order_detail|
      total += order_detail.piece
    end
    return total
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum create_status: {
    production_not_possible: 0,
    production_pending: 1,
    in_production: 2,
    production_complete: 3
  }
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
    before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer= Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end


  def update
    @customer = Customer.find(params[:id])
   if @customer.update(customer_params)
        redirect_to admin_customer_path(@customer.id)
   else
      render :edit
   end
  end
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_cord, :address, :telephone_number, :email, :is_active )
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!

  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price_before_tax, :genre_id, :is_selling_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_payment = 0
    @postage = @order.postage
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
        if  @order.status == "入金確認"
            @order_details.update_all(create_status: 1)
        end
    end
     redirect_to admin_order_path(@order.id)
    # @order_details = OrderDetail.find(params[:id])
    # @order_details.update(order_detail_params)
    # redirect_to admin_order_path(@order.id)
  end

  def order_params
     params.require(:order).permit(:status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<%= render 'layouts/admin_header' %>
<div class="container">
  <div class="row">
    <div class="col">
      <h2> <%= @customer.last_name + @customer.first_name %> さんの会員情報編集</h2>
      <%= form_with model: @customer, url: admin_customer_path(@customer.id) do |f| %>
      <table>
        <tbody>
          <tr>
            <td>会員id</td>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <td>氏名</td>
            <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></td>
            <td><%= f.text_field :first_name, autocomplete: "first_name" %></td>
          </tr>
          <tr>
            <td>フリガナ</td>
            <td><%= f.text_field :last_name_kana, autocomplete: "last_name_kana" %></td>
            <td><%= f.text_field :first_name_kana, autocomplete: "first_name_kana"%></td>
          </tr>
          <tr>
            <td>郵便番号</td>
            <td><%= f.text_field :post_cord, autocomplete: "post_cord"  %></td>
          </tr>
          <tr>
            <td>住所</td>
            <td><%= f.text_field :address, autocomplete: "adresses" %></td>
          </tr>
          <tr>
            <td>電話番号</td>
            <td><%= f.text_field :telephone_number, autocomplete: "telephone_number" %></td>
          </tr>
          <tr>
            <td>メールアドレス</td>
            <td><%= f.text_field :email, autocomplete: "new-password" %></td>
          </tr>
          <tr>
            <td>会員ステータス</td>
            <td><%=f.radio_button :is_active, true %></td>
            <td><%=f.label :is_active,"有効" %></td>
            <td><%=f.radio_button :is_active, false %></td>
            <td><%=f.label :is_active, "退会" %></td>
          </tr>
          <tr>
            <td><%= f.submit '変更を保存', class: "btn btn-success" %></td>
          </tr>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<%= render 'layouts/admin_header' %>
<div class="container">
  <div class="row">
    <div class="col">
      <h2>会員一覧</h2>
      <table class="table">
        <thead>
          <tr class="table-secondary">
            <th>会員id</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class:"text-dark"%></td>
            <td><%= customer.email %></td>
            <td><% if customer.is_active  %>
            <p class="text-success">有効</p>
            <% else %>
            <p>退会</p>
            <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= paginate @customers %>

app/views/admin/customers/show.html.erb
<%= render 'layouts/admin_header' %>
<div class="container">
  <div class="row">
    <div class="col">
  <h2> <%= @customer.last_name + @customer.first_name %> さんの会員詳細</h2>
  <table>
    <tbody>
    <tr>
      <th>会員id</th>
      <td></td>
      <td><%= @customer.id%></td>
    </tr>
    <tr>
      <th>氏名</th>
      <td></td>
      <td><%= @customer.last_name %>  <%= @customer.first_name %></td>
    </tr>
    <tr>
      <th>フリガナ</th>
      <td></td>
      <td><%= @customer.last_name_kana %>  <%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <th>郵便番号</th>
      <td></td>
      <td><%= @customer.post_cord %></td>
    </tr>
    <tr>
      <th>住所</th>
      <td></td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <th>電話番号</th>
      <td></td>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td></td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <th>会員ステータス</th>
      <td></td>
      <td><% if @customer.is_active %>
            <p class="text-success">有効</p>
          <% else %>
            <p>退会</p>
          <% end %>
      </td>
    </tr>
  </table>
  <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
  <%= link_to "注文履歴一覧を見る", admin_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>