config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do #routing errorが出たのでscope moduleを付けておきました。
    root to: 'homes#top'
    get "about"=>"homes#about"

    get 'customers/mypage'=>"customers#show"
    get "customers/mypage/edit"=>"customers#edit"
    patch "customers/mypage"=>"customers#update"
    get 'customers/mypage/confirm'=>"customers#confirm"
    patch 'customers/mypage/withdraw'=>"customers#withdraw"

    post 'orders/confirm'=>'orders#confirm'
    get "orders/complete"=>"orders#complete"
    resources :orders, only: [:new, :create, :index, :show]


    delete "cart_items/destroy_all"=>"cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
  end

  namespace :admin do
    get  "/"=>"homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :shipping_post_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

  def address_display
  '〒' + shipping_post_code + ' ' + shipping_address + ' ' + shipping_name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.item_total_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

#以下バリデーション　数字のみ漢字のみカナのみなど
  validates :telephone_number, numericality: {only_integer: true}, length: { in: 10..11}
  validates :post_cord, numericality: {only_integer: true}, length: { is: 7}
  validates :last_name, format:{with: /\p{Han}/}
  validates :first_name, format:{with: /\p{Han}/}
  validates :last_name_kana, format:{with: /\A[ァ-ヶー]+\z/}
  validates :first_name_kana, format:{with: /\A[ァ-ヶー]+\z/}

  def address_display
  '〒' + post_cord + ' ' + address + ' '
  end
  
  def fullname
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items
  has_many :order_details
  has_many :orders, through: :order_details #n:mの関係を表現するアソシエーション。
  belongs_to :genre

  #バリデーション
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price_before_tax, presence: true
  
  #税込表示価格
  def item_total_price
    (price_before_tax*1.1).floor
  end

  #カート内で商品の画像を表示させる
  def display_image
    if image.attached?
      image.variant(resize_to_limit: [100, 100]).processed
    else
      file_path = Rails.root.join('app/assets/images/no_image.png')
      file_path.to_s
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, through: :order_details #n:mの関係を表現するアソシエーション。
  has_many :order_details, dependent: :destroy

  enum payment: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting_payment: 0,
    confirm_payment: 1,
    shipped: 2,
    out_of_delivery: 3,
    delivered: 4
  }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

  def total_piece
    total = 0
    order_details.each do |order_detail|
      total += order_detail.piece
    end
    return total
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum create_status: {
    production_not_possible: 0,
    production_pending: 1,
    in_production: 2,
    production_complete: 3
  }
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  # ストロングパラメータ
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!

  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price_before_tax, :genre_id, :is_selling_status)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total_payment = 0
    @postage = @order.postage
  end

  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
        if  @order.status == "入金確認"
            @order_details.update_all(create_status: 1)
        end
    end
     redirect_to admin_order_path(@order.id)
    # @order_details = OrderDetail.find(params[:id])
    # @order_details.update(order_detail_params)
    # redirect_to admin_order_path(@order.id)
  end

  def order_params
     params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<%= render 'layouts/admin_header' %>
<html>
  <body>
    <main>
      <p id= "notice"></p>
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <h4>ジャンル編集</h4>

            <% if @genre.errors.any? %>
              <%= @genre.errors.count %>件のエラーが発生しました
              <ul>
                <% @genre.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>

            <%= form_with model: @genre, url: admin_genre_path(@genre), method: :patch do |f| %>
            <p>ジャンル名
              <td><%= f.text_field :name, class:'m-4' %></td>

              <td><%= f.submit '変更を保存', class:'btn btn-success m-4' %></td>
            </p>

            <% end %>
          </div>
          <div class= "col-sm-6"></div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/admin/genres/index.html.erb
<%= render 'layouts/admin_header' %>
<html>
  <body>
    <main>
      <p id= "notice"></p>
      <div class= "container">
        <div class= "row">
          <div class= "col-sm-12">
            <h4>ジャンル機能</h4>

            <% if @genre.errors.any? %>
              <%= @genre.errors.count %>件のエラーが発生しました
              <ul>
                <% @genre.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>

            <%= form_with model: @genre, url: admin_genres_path do |f| %>
              <p>ジャンル名
                <td><%= f.text_field :name, class:'m-4', :placeholder => "ジャンル名" %></td>

                <td><%= f.submit '新規登録', class:'btn btn-success m-4' %></td>
              </p>
            <% end %>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class= "col-sm-6">
            <table class='table'>
              <tr class="table-secondary">
                <th colspan="2">ジャンル</th>
              </tr>
              <% @genres.each do |genre| %>

              <tr class="border-bottom">
                <td><%= genre.name %></td>

                <td style="width: 150px;"><%= link_to '編集する', edit_admin_genre_path(genre), class:'btn btn-success'  %></td>
              </tr>

              <% end %>
            </table>
          </div>
          <div class= "col-sm-6"></div>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/admin/items/edit.html.erb
<%= render 'layouts/admin_header' %>
<div class="container">
  <% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <div class="row mt-3">
    <h4>商品編集</h4>
  </div>

  <%=form_with model: @item, url: admin_item_path, method: :patch do |f| %>

  <div class="row mt-3 ml-5">
    <table class="table table-borderless">
      <tr>
        <th>商品画像</th>
        <td><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <th>商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th>商品説明</th>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <th>ジャンル</th>
        <td><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name) %></td>
      </tr>
      <tr>
        <th>税抜価格</th>
        <td><%= f.text_field :price_before_tax %>円</td>
      </tr>
      <tr>
        <th>販売ステータス</th>
        <td>
          <%= f.label :is_selling_status, "販売中" %><%= f.radio_button :is_selling_status, :true %>
          <%= f.label :is_selling_status, "販売停止中" %><%= f.radio_button :is_selling_status, :false %>
        </td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit "変更を保存", class: "btn btn-lg btn-success rounded" %></td>
      </tr>
    </table>
  </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<%# 商品作成リンクがうまくいかないので仮置きで真横に+おいてます %>
<%= render 'layouts/admin_header' %>

<div class="container">
  <div class="row mt-5">
    <div class="col-3">
      <h4>商品一覧</h4>
    </div>
    <div class="col text-right">
      <%= link_to new_admin_item_path, class:"btn btn-light" do %>
        <i class="fa-solid fa-plus"></i>
      <% end %>
    </div>
  </div>

  <div class="row mt-3">
    <table class="table table-borderless">
      <tr>
        <th class="table-secondary">商品ID</th>
        <th class="table-secondary">商品名</th>
        <th class="table-secondary">税抜価格</th>
        <th class="table-secondary">ジャンル</th>
        <th class="table-secondary">ステータス</th>
      </tr>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item), class:"text-dark" %></td>
        <td><%= number_with_delimiter(item.price_before_tax, delimiter: ',') %></td>
        <td><%= item.genre.name %></td>
        <td>
            <% if item.is_selling_status? %>
              <b class="text-success">販売中</b>
            <% else %>
              <b class="text-secondary">販売停止中</b>
            <% end %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
  <div class="d-flex justify-content-center mt-4">
    <%= paginate @items %>
  </div>
</div>

app/views/admin/items/new.html.erb
<%= render 'layouts/admin_header' %>
<div class="container">
  <div class="row mt-5 ml-2">
    <h3>商品新規登録</h3>
  </div>

  <%= form_with model: @item, url: admin_items_path do |f| %>

  <div class="row mt-2">

    <div class="col-md-6 offset-md-3">
      <table class="table table-borderless">
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field :image, accept: "image/*" %></td>
        </tr>
        <tr>
          <th><%= f.label :name, "商品名" %></th>
          <td><%= f.text_field :name, autocomplete: "name", class:"form-control", placeholder: "商品名" %></td>
         </tr>
        <tr>
          <th><%= f.label :introduction, "商品説明" %></th>
          <td><%= f.text_area :introduction, autocomplete: "introduction", class:"form-control", placeholder: "ここに説明文を記述します" %></td>
        </tr>
        <tr>
          <th><%= f.label :genre_id, "ジャンル" %></th>
          <td class="selectbox-002 "><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), class:"form-control" %></td>
        </tr>
        <tr>
          <th><%= f.label :price_before_tax, "税抜価格" %></th>
          <td><%= f.text_field :price_before_tax, autocomplete: "price_before_tax", class:"form-control" %></td>
          <td>円</td>
        </tr>
        <tr>
          <th><%= f.label :is_selling_status, "販売ステータス" %></th>
          <td><%= f.label :is_selling_status, "販売中" %><%= f.radio_button :is_selling_status, :true %>
              <%= f.label :is_selling_status, "販売停止中" %><%= f.radio_button :is_selling_status, :false %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "新規登録", class: "btn btn-lg btn-success rounded"  %></td>
        </tr>
      </table>
    </div>
  </div>

  <% end %>
</div>

app/views/admin/items/show.html.erb
<%= render 'layouts/admin_header' %>
<div class="container">
  <div class="row mt-5">
    <h3>商品詳細</h3>
  </div>

  <div class="row mt-3">
    <div class="col-4">
      <%= image_tag @item.image, size: "200x200" %>
    </div>
    <div class="col-7 ml-2">
      <table class="table table-borderless">
        <div class="mb-3">
          <th>商品名</th>
          <td><%= @item.name %></td>
        </div>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格<br>(税抜価格)</th>
          <td><%= number_with_delimiter(@item.item_total_price, delimiter: ',') %>(<%= number_with_delimiter(@item.price_before_tax, delimiter: ',') %>)円</td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <% if @item.is_selling_status? %>
              <b class="text-success">販売中</b>
            <% else %>
              <b class="text-secondary">販売停止中</b>
            <% end %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-lg btn-success rounded" %></td>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<%= render 'layouts/admin_header' %>
<div class="container">
  <div class="row">
    <div class="col">
      <h2>注文履歴詳細</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>購入者</td>
            <td><%= link_to @order.name, admin_customer_path(@order.id), class: "text-dark" %></td>
          </tr>
          <tr>
            <td>注文日</td>
            <td><%= @order.created_at %></td>
          </tr>
          <tr>
            <td>配送先</td>
            <td><%= @order.address %></td>
          </tr>
          <tr>
            <td>支払方法</td>
            <td><%= @order.payment_i18n %></td>
          </tr>
          <tr>
            <td>注文ステータス</td>
            <td>
              <%= form_with model: @order, url: admin_order_path do |f| %>
              <%= f.select :status, Order.statuses.keys.map { |k| [t("enums.order.status.#{k}"), k] } %>
              <%= f.submit "更新", class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table>
        <thead>
          <tr class="table-secondary">
          <!--item-->
          <th>商品名</th>
          <!--order_detail-->
          <th>単価（税込）</th>
          <!--order_detail-->
          <th>数量</th>
          <!--order_detail、個数*価格-->
          <th>小計</th>
          <!--order_detail-->
          <th>製作ステータス</th>
          </tr>
        </thead>
      <tbody>
        <% @order_details.each do |order_detail| %>
        <tr>
          <td><%= order_detail.item.name %></td>
          <td><%= (order_detail.price * 1.1).floor %></td>
          <td><%= order_detail.piece %></td>
          <td>
            <%= (order_detail.price * 1.1).floor*order_detail.piece %>
          </td>
          <% @total_payment += (order_detail.price * 1.1).floor*order_detail.piece %>
          <td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail) do |f| %>
              <%= f.select :create_status, OrderDetail.create_statuses.keys.map { |k| [t("enums.order_detail.create_status.#{k}"), k] } %>
              <%= f.submit "更新", class: "btn btn-success" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
      <tbody>
        <tr>
          <td>商品合計</td>
          <td><%= @total_payment %></td>
        </tr>
        <tr>
          <td>送料</td>
          <td><%= @postage %></td>
        </tr>
        <tr>
          <td>請求金額合計</td>
          <td><%= @total_payment + @postage %></td>
        </tr>
      </tbody>
    </div>
  </div>
</div>