config/routes.rb
Rails.application.routes.draw do
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admin,skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do #routing errorが出たのでscope moduleを付けておきました。
    root to: 'homes#top'
    get "about"=>"homes#about"

    get 'customers/mypage'=>"customers#show"
    get "customers/mypage/edit"=>"customers#edit"
    patch "customers/mypage"=>"customers#update"
    get 'customers/mypage/confirm'=>"customers#confirm"
    patch 'customers/mypage/withdraw'=>"customers#withdraw"

    post 'orders/confirm'=>'orders#confirm'
    get "orders/complete"=>"orders#complete"
    resources :orders, only: [:new, :create, :index, :show]


    delete "cart_items/destroy_all"=>"cart_items#destroy_all"
    resources :cart_items, only: [:index, :update, :destroy, :create]


    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
  end

  namespace :admin do
    get  "/"=>"homes#top"
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  validates :shipping_post_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true

  def address_display
  '〒' + shipping_post_code + ' ' + shipping_address + ' ' + shipping_name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def subtotal
    item.item_total_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy

#以下バリデーション　数字のみ漢字のみカナのみなど
  validates :telephone_number, numericality: {only_integer: true}, length: { in: 10..11}
  validates :post_cord, numericality: {only_integer: true}, length: { is: 7}
  validates :last_name, format:{with: /\p{Han}/}
  validates :first_name, format:{with: /\p{Han}/}
  validates :last_name_kana, format:{with: /\A[ァ-ヶー]+\z/}
  validates :first_name_kana, format:{with: /\A[ァ-ヶー]+\z/}

  def address_display
  '〒' + post_cord + ' ' + address + ' '
  end
  
  def fullname
    last_name + first_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image

  has_many :cart_items
  has_many :order_details
  has_many :orders, through: :order_details #n:mの関係を表現するアソシエーション。
  belongs_to :genre

  #バリデーション
  validates :name, presence: true
  validates :image, presence: true
  validates :introduction, presence: true
  validates :genre_id, presence: true
  validates :price_before_tax, presence: true
  
  #税込表示価格
  def item_total_price
    (price_before_tax*1.1).floor
  end

  #カート内で商品の画像を表示させる
  def display_image
    if image.attached?
      image.variant(resize_to_limit: [100, 100]).processed
    else
      file_path = Rails.root.join('app/assets/images/no_image.png')
      file_path.to_s
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :items, through: :order_details #n:mの関係を表現するアソシエーション。
  has_many :order_details, dependent: :destroy

  enum payment: { credit_card: 0, transfer: 1 }

  enum status: {
    waiting_payment: 0,
    confirm_payment: 1,
    shipped: 2,
    out_of_delivery: 3,
    delivered: 4
  }
  enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

  def address_display
    '〒' + post_code + ' ' + address + ' ' + name
  end

  def total_piece
    total = 0
    order_details.each do |order_detail|
      total += order_detail.piece
    end
    return total
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum create_status: {
    production_not_possible: 0,
    production_pending: 1,
    in_production: 2,
    production_complete: 3
  }
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page])
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    before_action :authenticate_admin!

  def index
    @items=Item.page(params[:page])
  end

  def new
    @item=Item.new
  end

  def create
    @item=Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render :new
    end
  end

  def show
    @item=Item.find(params[:id])
  end

  def edit
    @item=Item.find(params[:id])
  end

  def update
    @item=Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :introduction, :price_before_tax, :genre_id, :is_selling_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header>
  <div class="p-1 border-bottom border-secondary">
    <nav>
      <div class="container">
        <div class="row">
          <div class="col">
            <%= link_to "LOGO", admin_path, class: "btn btn-outline-dark btn-lg"%>
          </div>
          <div class="col">
            <div class="d-flex flex-row-reverse bd-highlight">
              <ul class="nav pull-right nav-pills">
                <% if admin_signed_in? %>
                  <li>
                    <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "注文履歴一覧", admin_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark"  %>
                  </li>
                  <li>
                    <%= link_to "ログアウト", destroy_admin_session_path, class: "btn btn-outline-dark", method: :delete   %>
                  </li>
                <% else %>
                  <li>
                    <%= link_to "About", about_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to"新規登録", admin_session_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to"ログイン", admin_session_path, class: "btn btn-outline-dark" %>
                  </li>
                <% end %>
                <div class="search">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    <%= form_with(url:cart_items_path, scope: :post, local: true) do |f| %>
                      <%= f.text_field :search, placeholder: "キーワード検索" %>
                      <% f.submit %>
                    <% end %>
                </div>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_public_header.html.erb
<header>
  <div class="p-1 border-bottom border-secondary">
    <nav>
      <div class="container">
        <div class="row">
          <div class="col">
            <%= link_to "LOGO", root_path, class: "btn btn-outline-dark btn-lg"%>
          </div>
          <div class="col">
            <div class="d-flex flex-row-reverse bd-highlight">
              <ul class="nav pull-right nav-pills">
                <% if customer_signed_in? %>
                  <li>
                    <%= link_to "マイページ", customers_mypage_path, class: "btn btn-outline-dark"%>
                  </li>
                  <li>
                    <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "カート", cart_items_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "ログアウト", destroy_customer_session_path, class: "btn btn-outline-dark", method: :delete %>
                  </li>
                  <div><%= "ようこそ、"+ current_customer.last_name+"さん！" %></div>
                <% else %>
                  <li>
                    <%= link_to "About", about_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %>
                  </li>
                  <li>
                    <%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %>
                  </li>
                <% end %>
                <div class="search">
                    <i class="fa-solid fa-magnifying-glass"></i>
                    <%= form_with(url:cart_items_path, scope: :post, local: true) do |f| %>
                      <%= f.text_field :search, placeholder: "キーワード検索" %>
                      <% f.submit %>
                    <% end %>
                </div>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <script src="https://kit.fontawesome.com/2487941ad8.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>